### ISSUE TITLE
to many roundtrips

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#4]
lets say we have 100 Products on ysws...

what we currently do is get all of them with one call to the Wemalo api ( API: 1, ES: 0 )
then we test if the product exists, that's 100 calls to ES (API:1, ES: 100)
then we run 100 calls to get the stocks from Wemalo (API: 101, ES: 100)
then we we loop over all products to construct an array to loop over...
to then loop over all products and call updateStock for them. 
updateStock first gets an item from the DB and then sets it, so thats 2 calls per update so another 200 calls to ES (API: 101, ES: 300)

this is really expensive (outgoing traffic, incomming traffic, runtime, db locks, etc)

i believe ideally we can get this down to 1 call to the API and 1 call to ES..

**Comment by alexlemaire** [comment]
**Update post Slack meeting**

Situation post refactoring:
- `kaskadi-get-ysws-stocks-lambda` does
  - 1 call to ES to get time of last stock update for YSWS stocks
  - 1 call to YSWS to retrieve stock changes since last update
  - 1 call through AWS infrastructure to invoke `kaskadi-update-stocks-lambda` if stocks have changed
- `kaskadi-update-stocks-lambda` does:
  - 1 call to ES for bulk update of stocks
  - 1 call to ES to update timestamp for last stock update
- `kaskadi-stock-report-lambda` does:
  - 1 call to ES to retrieve stock info
  - if we have more than 500 products returned then we keep calling until we retrieved all data. Can increase that limit but I thought 500 products on YSWS was already quite a high amount

Closing for now.
