### ISSUE TITLE
unnecessary switch

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#6]
we only have two cases so why use switch? and why an overhead of an additional function/module?

https://github.com/kaskadi/kaskadi-stock-update-lambda/blob/b6fae1e31400837a1c920d11eaaf100f297e15e8/kaskadi-stock-update-lambda.js#L7

could just be:

```
if (event.source === 'aws.events'){
// scheduled call
}else{
// api call
}
```

**Comment by alexlemaire** [comment]
**Update post Slack meeting**

No more switch after refactoring! :tada: 

The only reason for that function before was that unfortunately Lambda doesn't provide a way to know the event origin since the `event` object is not standardized through all triggers for Lambdas... An event from API looks completely different than SNS for example, which imo is a bit weird implementation when they could have used `event.type` and `event.payload` instead but well

Closing for now.
