### ISSUE TITLE
return updated stocks

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-get-ysws-stocks-lambda#8]
when we update the stock, why not just return them here as do just do have them available?
this might save another roundtrip of getting the updated stocks for display...

**Comment by alexlemaire** [comment]
**Update post Slack meeting**

With the new approach I'm calling `kaskadi-update-stocks-lambda` asynchronously to not get billed twice for the runtime.

@Holger-Will for now I'm returning a simple confirmation message. Do we want to send information about stock change back to the client so that it does its partial update on its side with the info received from the lambda?

**Comment by alexlemaire** [comment]
The lambda now returns the new stocks data (or an empty array if there was no change since last DB update).

This way we don't need to first hit this endpoint to update stocks and then hit our DB for new stock info.
